Update upcall

diff --git a/upcall b/upcall
--- a/upcall
+++ b/upcall
@@ -1,8 +1,20 @@
 #!/bin/bash
 
+# stop on errors
+set -e
+
+scriptname=$(basename $0)
+pidfile="/var/run/${scriptname}"
+
+# lock it
+exec 200>$pidfile
+flock -n 200 || exit 1
+pid=$$
+echo $pid 1>&200
+
 count=$(</opt/rclone/scripts/upcount)
 size=$(df -k /dev/sda2 | tail -1 | awk '{print $3}')
-if [ "$size" -gt "734003200" ]; then
+if [ "$size" -gt "534003200" ]; then
 bash /opt/rclone/scripts/upload_cloud${count}
 else
 echo "Not full yet"
